import fs from 'node:fs';
import path from 'node:path';
import localidades from './src/localidades.json' with { type: 'json' };

const PHONE='641 589 394';
const TEL='+34641589394';
const WA='34641589394';
const hash=s=>[...s].reduce((a,c)=>(a+c.charCodeAt(0))%997,0);
const headings=[l=>`Servicio técnico de antenas en ${l} y alrededores`,l=>`Técnico de antenas en ${l}: atención directa`,l=>`Antenista en ${l} para instalación y reparación`,l=>`Atención técnica de antenas en ${l}`];
const intros=['Atención para viviendas y comunidades, con contacto directo para explicar la avería o instalación que necesitas.','Servicio de proximidad para averías e instalaciones de antena, con atención directa desde el primer contacto.','Soluciones para recepción de TV, instalaciones colectivas y sistemas de acceso en viviendas y comunidades.','Cuéntanos el problema y recibe atención directa para valorar la reparación o instalación necesaria.'];
const css=`<style id="town-trust-style">
.town-trust{padding:8px 0 34px}.town-trust-card{text-align:center;padding:28px 24px;border:1px solid #dce5ec;border-radius:15px;background:linear-gradient(135deg,#f8fbfd,#eef6fb);box-shadow:0 9px 24px rgba(16,45,72,.07)}.town-trust-stars{color:#e6a800;font-size:25px;letter-spacing:4px;line-height:1;margin-bottom:10px}.town-trust h2{margin:0 0 8px;color:#0a3f73}.town-trust-lead{max-width:790px;margin:0 auto;color:#536373}.town-trust-points{display:flex;justify-content:center;flex-wrap:wrap;gap:8px 11px;margin:18px auto 20px}.town-trust-points span{padding:8px 11px;border:1px solid #d7e4ed;border-radius:999px;background:#fff;color:#29465f;font-size:13px;font-weight:700}.town-trust-actions{display:flex;align-items:center;justify-content:center;gap:12px;flex-wrap:wrap}.town-trust-phone{font-size:24px;font-weight:900;color:#d92128!important}
#porteros .detail{grid-template-columns:1fr!important;gap:0!important}#porteros .detail>aside{display:none!important}#porteros .detail>div{max-width:none!important;width:100%}
.old-doorphones{margin:20px 0 4px}.old-doorphones-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.old-doorphones-grid figure{margin:0;display:flex;align-items:center;justify-content:center;height:190px;padding:10px;background:#fff;border:1px solid #dce5ec;border-radius:11px;overflow:hidden}.old-doorphones-grid img{width:100%;height:100%;object-fit:contain}.old-doorphones-grid figure:nth-child(2) img{transform:scale(1.18)}.old-doorphones-copy,.amp-copy{margin-top:13px;padding:13px 15px;background:#f6f9fb;border-radius:9px;color:#465b6d}.old-doorphones-copy strong,.amp-copy strong{display:block;color:#0a3f73;font-size:17px;margin-bottom:3px}.old-doorphones-copy p,.amp-copy p{margin:0;font-size:14px;line-height:1.55}.doorphone-brands{display:flex;align-items:center;flex-wrap:wrap;gap:8px;margin:17px 0 0}.doorphone-brands-label{font-size:13px;font-weight:800;color:#536373;margin-right:2px}.doorphone-brand{display:inline-flex;align-items:center;padding:7px 11px;border:1px solid #d7e4ed;border-radius:999px;background:#fff;color:#0a3f73;font-size:13px;font-weight:800;line-height:1}
.amp-gallery{margin:20px 0 4px}.amp-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.amp-grid figure{margin:0;height:180px;padding:10px;display:flex;align-items:center;justify-content:center;background:#fff;border:1px solid #dce5ec;border-radius:11px;overflow:hidden}.amp-grid img{width:100%;height:100%;object-fit:contain}
#reparacion .help strong{font-size:24px;line-height:1.15}#reparacion .help span{line-height:1.5}#reparacion .help .help-services{display:block;margin:4px 0 15px;font-size:14px;opacity:.95}#reparacion .help a{font-size:16px}
@media(hover:hover) and (pointer:fine){.town-trust-card,.town-trust-points span,.town-trust-phone,.old-doorphones-grid figure,.doorphone-brand,.amp-grid figure{transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.town-trust-card:hover{box-shadow:0 12px 28px rgba(16,45,72,.10)}.town-trust-points span:hover,.old-doorphones-grid figure:hover,.doorphone-brand:hover,.amp-grid figure:hover{transform:translateY(-1px);border-color:#bfd4e3}.town-trust-phone:hover{transform:translateY(-1px)}}
@media(max-width:640px){.town-trust{padding:2px 0 24px}.town-trust-card{padding:23px 13px;border-radius:13px}.town-trust-stars{font-size:22px;letter-spacing:3px}.town-trust h2{font-size:24px}.town-trust-lead{font-size:14px}.town-trust-points{gap:7px;margin:15px 0 18px}.town-trust-points span{font-size:12px;padding:7px 9px}.town-trust-phone{font-size:21px}.old-doorphones{margin-top:15px}.old-doorphones-grid{gap:6px}.old-doorphones-grid figure{height:108px;padding:5px;border-radius:8px}.old-doorphones-grid figure:nth-child(2) img{transform:scale(1.22)}.old-doorphones-copy,.amp-copy{padding:11px 12px}.old-doorphones-copy strong,.amp-copy strong{font-size:15px}.old-doorphones-copy p,.amp-copy p{font-size:12px}.doorphone-brands{gap:6px;margin-top:14px}.doorphone-brands-label{width:100%;font-size:12px}.doorphone-brand{font-size:12px;padding:6px 9px}.amp-gallery{margin-top:15px}.amp-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.amp-grid figure{height:125px;padding:6px;border-radius:8px}}
@media(prefers-reduced-motion:reduce){.town-trust-card,.town-trust-points span,.town-trust-phone,.old-doorphones-grid figure,.doorphone-brand,.amp-grid figure{transition:none!important}}</style>`;
for(const d of localidades){
 const file=path.join('public',d.provinciaSlug,d.slug,'index.html');let h=fs.readFileSync(file,'utf8');const v=hash(`${d.provinciaSlug}/${d.slug}`)%headings.length;
 h=h.replace(`<div class="kicker">Técnico de antenas en ${d.localidad}</div>`,'<div class="kicker">Hoy estamos cerca de tu casa</div>');
 const gallery=`<div class="old-doorphones"><div class="old-doorphones-grid"><figure><img src="/assets/portero-antiguo-1.jpg" loading="lazy" alt="Placa de portero automático antigua para reparar o renovar en ${d.localidad}"></figure><figure><img src="/assets/portero-antiguo-2.jpg" loading="lazy" alt="Portero automático Fermax antiguo para reparación o sustitución en ${d.localidad}"></figure><figure><img src="/assets/portero-antiguo-3.jpg" loading="lazy" alt="Placa de portero Tegui antigua para reparar o cambiar por videoportero en ${d.localidad}"></figure></div><div class="old-doorphones-copy"><strong>¿Tienes un portero antiguo?</strong><p>Reparamos placas de calle, telefonillos, pulsadores, fuentes y cableado. Si el sistema está obsoleto, también podemos renovarlo o sustituirlo por un portero o videoportero actual.</p></div></div>`;
 if(!h.includes('class="old-doorphones"')) h=h.replace(/(<section class="band" id="porteros">[\s\S]*?<h2>Instalación, reparación y renovación de porteros automáticos y videoporteros en [^<]+<\/h2>[\s\S]*?<p>[^<]*<\/p>)/i,`$1${gallery}`);
 const brands=`<div class="doorphone-brands" aria-label="Marcas habituales de porteros automáticos"><span class="doorphone-brands-label">Trabajamos con:</span><span class="doorphone-brand">Fermax</span><span class="doorphone-brand">Tegui</span><span class="doorphone-brand">Golmar</span><span class="doorphone-brand">Comelit</span><span class="doorphone-brand">Bticino</span><span class="doorphone-brand">Legrand</span><span class="doorphone-brand">Fringe</span><span class="doorphone-brand">Galak</span></div>`;
 h=h.replace(/(<section class="band" id="porteros">[\s\S]*?)<p class="brands-note">[\s\S]*?<\/p>/i,`$1${brands}`);
 const ampGallery=`<div class="amp-gallery"><div class="amp-grid"><figure><img src="/assets/amplificador-alcad-interior.jpg" loading="lazy" alt="Amplificador de interior Alcad para antena en ${d.localidad}"></figure><figure><img src="/assets/amplificador-alcad-mastil.jpg" loading="lazy" alt="Amplificador de mástil Alcad para antena TDT en ${d.localidad}"></figure><figure><img src="/assets/amplificador-televes.jpg" loading="lazy" alt="Amplificador Televés para reparación de antena en ${d.localidad}"></figure><figure><img src="/assets/amplificador-satelite-rover-ek.jpg" loading="lazy" alt="Amplificador y equipo de satélite Rover EK en ${d.localidad}"></figure></div><div class="amp-copy"><strong>Reparación y sustitución de amplificadores</strong><p>Reparamos amplificadores de interior y de mástil, fuentes de alimentación, centrales de amplificación y equipos de satélite. Revisamos primero la avería para sustituir únicamente lo necesario.</p></div></div>`;
 const antennaBrands=`<div class="doorphone-brands" aria-label="Marcas habituales de antenas y amplificación"><span class="doorphone-brands-label">Trabajamos con:</span><span class="doorphone-brand">Televés</span><span class="doorphone-brand">Alcad</span><span class="doorphone-brand">Ikusi</span><span class="doorphone-brand">Fagor</span><span class="doorphone-brand">Rover</span><span class="doorphone-brand">EK</span><span class="doorphone-brand">FTE Maximal</span><span class="doorphone-brand">Fringe</span></div>`;
 h=h.replace(/(<section class="band" id="reparacion">[\s\S]*?)<p class="brands-note">[\s\S]*?<\/p>/i,`$1${ampGallery}${antennaBrands}`);
 const helpBox=`<aside class="help"><strong>¿Tienes una avería?</strong><span>Habla directamente con el técnico.</span><span class="help-services">Antenas · Porteros · Videoporteros · Amplificación</span><a href="tel:${TEL}">☎ ${PHONE}</a></aside>`;
 h=h.replace(/(<section class="band" id="reparacion">[\s\S]*?)<aside class="help">[\s\S]*?<\/aside>/i,`$1${helpBox}`);
 const block=`<section class="town-trust" aria-label="Servicio técnico en ${d.localidad}"><div class="wrap"><div class="town-trust-card"><div class="town-trust-stars" aria-hidden="true">★★★★★</div><h2>${headings[v](d.localidad)}</h2><p class="town-trust-lead">${intros[v]}</p><div class="town-trust-points"><span>✓ Antenas individuales y colectivas</span><span>✓ Instalación y reparación TDT</span><span>✓ Porteros automáticos y videoporteros</span><span>✓ Averías y falta de señal</span></div><div class="town-trust-actions"><a class="town-trust-phone" href="tel:${TEL}">☎ ${PHONE}</a><a class="btn green" href="https://wa.me/${WA}">WhatsApp</a></div></div></div></section>`;
 if(!h.includes('id="town-trust-style"'))h=h.replace('</head>',css+'</head>');if(!h.includes('class="town-trust"')){if(h.includes('<section class="contact"'))h=h.replace('<section class="contact"',block+'<section class="contact"');else if(h.includes('<footer'))h=h.replace('<footer',block+'<footer');else h=h.replace('</main>',block+'</main>')}fs.writeFileSync(file,h);
}
console.log(`Proximidad, porteros antiguos, amplificadores, marcas y cartel de averias añadidos a ${localidades.length} localidades.`);
