import fs from 'node:fs';
import path from 'node:path';

const ROOT='public';
const TOWN_IMAGE='https://images.unsplash.com/photo-1541698265912-0a5606dcf0f8?auto=format&fit=crop&fm=jpg&q=82&w=1600';
const MOBILE_IMAGE='/assets/cobertura-movil.png';
const ELECTRIC_IMAGE='https://images.pexels.com/photos/257736/pexels-photo-257736.jpeg?auto=compress&cs=tinysrgb&w=1200';
const forbidden=['Una página completa para cada localidad','Todo en el mismo HTML','Servicios, zona, preguntas y contacto funcionan mediante anclas internas'];

function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const p=path.join(dir,e.name);return e.isDirectory()?walk(p):[p]})}
function injectLayout(h){h=h.replace(/<style data-layout-services="6">[\s\S]*?<\/style>/i,'').replace(/<style data-home-services="6">[\s\S]*?<\/style>/i,'');return h.replace('</head>',`<style data-layout-services="6">@media(min-width:1000px){.wrap,.w{width:min(1280px,calc(100% - 48px));max-width:1280px}.cards{grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:18px}.card img{height:175px}}@media(max-width:850px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:640px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px}.card{min-width:0}.card h3{overflow-wrap:anywhere}}</style></head>`)}
function normalizeTownCards(h){const m=h.match(/(<section class="services wrap" id="servicios">[\s\S]*?<div class="cards">)([\s\S]*?)(<\/div><\/section>)/i);if(!m)return h;const cards=[...m[2].matchAll(/<a class="card"[\s\S]*?<\/a>/gi)].map(x=>x[0]);const base=cards.filter(c=>!/Cobertura móvil|Reparaciones eléctricas|telefonia-movil|reparaciones-electricas/i.test(c)).slice(0,4);const mobile=`<a class="card" href="#telefonia-movil"><img src="${MOBILE_IMAGE}" alt="Antena de telefonía móvil instalada en vivienda"><h3>Cobertura móvil</h3><p>Antenas de telefonía móvil para viviendas con señal débil.</p></a>`;const electric=`<a class="card" href="#reparaciones-electricas"><img src="${ELECTRIC_IMAGE}" alt="Cuadro eléctrico de vivienda"><h3>Reparaciones eléctricas</h3><p>Instalación y reparación de automáticos en cuadros eléctricos de vivienda.</p></a>`;return h.replace(m[0],m[1]+base.join('')+mobile+electric+m[3])}
function normalizeHomeCards(h){const m=h.match(/(<section id="servicios" class="section">[\s\S]*?<div class="cards">)([\s\S]*?)(<\/div><\/div><\/section><section id="zonas")/i);if(!m)return h;const cards=[...m[2].matchAll(/<article class="card">[\s\S]*?<\/article>/gi)].map(x=>x[0]);const base=cards.filter(c=>!/Cobertura móvil|Reparaciones eléctricas/i.test(c)).slice(0,4);const mobile=`<article class="card"><img src="${MOBILE_IMAGE}" alt="Antena de telefonía móvil instalada en vivienda"><div><h3>Cobertura móvil</h3><p>Antenas de telefonía para mejorar la señal en viviendas unifamiliares.</p></div></article>`;const electric=`<article class="card"><img src="${ELECTRIC_IMAGE}" alt="Cuadro eléctrico de vivienda"><div><h3>Reparaciones eléctricas</h3><p>Instalación y reparación de automáticos en cuadros eléctricos de vivienda.</p></div></article>`;return h.replace(m[0],m[1]+base.join('')+mobile+electric+m[3])}
function dedupeMobileSections(h){const re=/<section class="twocol wrap" id="telefonia-movil">[\s\S]*?<\/section>/gi;const matches=[...h.matchAll(re)];if(matches.length<=1)return h;let kept=false;return h.replace(re,s=>{if(!kept){kept=true;return s}return ''})}

const htmlFiles=walk(ROOT).filter(p=>p.endsWith('.html'));let townCount=0;
for(const file of htmlFiles){let h=fs.readFileSync(file,'utf8');const rel=path.relative(ROOT,file).split(path.sep);if(rel.length===1&&rel[0]==='index.html'){h=h.replaceAll('Porteros y videoporteros','Porteros automáticos y videoporteros');h=normalizeHomeCards(h);h=injectLayout(h);fs.writeFileSync(file,h);continue}if(rel.length!==3||rel[2]!=='index.html')continue;const m=h.match(/<h1>Antenista en ([^<]+)<\/h1>/i);if(!m)continue;const town=m[1].trim();
 h=h.replace(/(<div class="localpic"><img src=")[^"]+(" alt="[^"]+">)/i,`$1${TOWN_IMAGE}$2`);h=h.replaceAll('Porteros y videoporteros','Porteros automáticos y videoporteros').replaceAll('Reparación de porteros y videoporteros','Reparación de porteros automáticos y videoporteros').replaceAll('porteros y videoporteros','porteros automáticos y videoporteros');h=normalizeTownCards(h);h=dedupeMobileSections(h);
 if(!h.includes('id="telefonia-movil"')){const b=`<section class="twocol wrap" id="telefonia-movil"><div><div class="kicker">Cobertura móvil</div><h2>Antenas de telefonía móvil en ${town}</h2><p>Instalamos antenas exteriores y soluciones de recepción para mejorar la cobertura de telefonía móvil en viviendas unifamiliares con señal débil o zonas interiores con poca cobertura. Primero comprobamos la señal disponible para recomendar una solución adecuada.</p></div><aside class="sidebox"><strong>Mejor señal en casa</strong><p>Orientación, cableado y ubicación de la antena adaptados a la vivienda y a la cobertura disponible en la zona.</p></aside></section>`;h=h.replace('<section class="band" id="porteros">',b+'<section class="band" id="porteros">')}
 if(!h.includes('id="reparaciones-electricas"')){const b=`<section class="twocol wrap" id="reparaciones-electricas"><div><div class="kicker">Electricidad en el hogar</div><h2>Reparaciones eléctricas en el hogar en ${town}</h2><p>Realizamos pequeñas reparaciones eléctricas en viviendas, incluida la instalación y sustitución de automáticos, magnetotérmicos y otros elementos del cuadro eléctrico doméstico.</p></div><aside class="sidebox"><strong>Cuadros eléctricos de vivienda</strong><p>Revisamos el problema antes de sustituir componentes y actuamos sobre protecciones y elementos del cuadro cuando la intervención corresponde a una instalación doméstica.</p></aside></section>`;h=h.replace('<section class="zone wrap" id="zona">',b+'<section class="zone wrap" id="zona">')}
 h=injectLayout(h);fs.writeFileSync(file,h);townCount++}
const failures=[];for(const file of htmlFiles){const h=fs.readFileSync(file,'utf8');for(const t of forbidden)if(h.includes(t))failures.push(`${file}: ${t}`)}if(failures.length){console.error('Build audit failed:\n'+failures.join('\n'));process.exit(1)}console.log(`Audited ${townCount} town pages: mobile section deduplicated and uploaded coverage image applied.`);
