import fs from 'node:fs';
import path from 'node:path';
import localidades from './src/localidades.json' with { type:'json' };

const STYLE=`<style id="town-backtop-style">.town-backtop{position:fixed;right:18px;bottom:18px;width:42px;height:42px;border:1px solid rgba(255,255,255,.22);border-radius:12px;background:#0a3f73;color:#fff;display:flex;align-items:center;justify-content:center;font-size:22px;font-weight:900;line-height:1;box-shadow:0 8px 22px rgba(10,63,115,.24);z-index:80;opacity:0;visibility:hidden;transform:translateY(8px);transition:opacity .18s ease,transform .18s ease,visibility .18s ease;cursor:pointer}.town-backtop.is-visible{opacity:.95;visibility:visible;transform:translateY(0)}.town-backtop:hover{opacity:1;transform:translateY(-1px)}.town-backtop:focus-visible{outline:3px solid #9fc3df;outline-offset:2px}.town-problems{padding:34px 0}.town-problems h2{margin:0 0 8px;color:#0a3f73;font-size:30px;line-height:1.15}.town-problems .lead{margin:0 0 18px;max-width:860px}.town-problems-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.town-problem{border:1px solid #dce5ec;border-radius:14px;background:#fff;padding:18px;box-shadow:0 10px 24px rgba(16,45,72,.07)}.town-problem strong{display:block;color:#0a3f73;font-size:18px;margin-bottom:6px}.town-problem p{margin:0;font-size:15px}.town-problems-cta{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.town-problems-cta a{display:inline-flex;align-items:center;justify-content:center;padding:11px 15px;border-radius:9px;font-weight:800;color:#fff!important;text-decoration:none}.town-problems-cta .call{background:#d92128}.town-problems-cta .wa{background:#10ad3e}@media(max-width:780px){.town-problems-grid{grid-template-columns:1fr}.town-problems{padding:28px 0}.town-problems h2{font-size:26px}}@media(max-width:640px){.town-backtop{right:12px;bottom:12px;width:40px;height:40px;border-radius:11px;font-size:20px}}@media(prefers-reduced-motion:reduce){.town-backtop{transition:none}}</style>`;
const BUTTON=`<button class="town-backtop" type="button" aria-label="Volver arriba" title="Volver arriba">↑</button>`;
const SCRIPT=`<script id="town-backtop-script">(()=>{const b=document.querySelector('.town-backtop');if(!b)return;const show=()=>b.classList.toggle('is-visible',window.scrollY>650);show();window.addEventListener('scroll',show,{passive:true});b.addEventListener('click',()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));})();</script>`;
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hash=s=>[...String(s)].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,7);
function problems(d){const n=esc(d.localidad),v=hash(`${d.provinciaSlug}/${d.slug}`)%4;const sets=[
[[`Faltan canales o la TDT se corta`,`Medimos la señal y revisamos antena, amplificación, cableado, repartidores y tomas para encontrar dónde empieza el problema en ${n}.`],[`Una vivienda recibe peor señal`,`Comparamos la señal con el resto de la instalación y comprobamos derivadores, conexiones y cableado antes de tocar la cabecera comunitaria.`],[`Portero o videoportero con avería`,`Revisamos placa, fuente de alimentación, telefonillos o monitores y cableado para valorar reparación o renovación. `]],
[[`Problemas en una antena colectiva`,`Comprobamos recepción, cabecera, fuentes, amplificadores y distribución para saber si la avería afecta a toda la comunidad o solo a una zona.`],[`Señal débil o pixelaciones`,`Seguimos la señal desde la antena hasta las tomas y localizamos pérdidas en amplificación, conexiones o red coaxial.`],[`Parabólica sin señal estable`,`Revisamos orientación, fijación, LNB, conectores y cableado antes de recomendar cambiar el equipo completo.`]],
[[`Amplificador o fuente averiados`,`Medimos entrada y salida, alimentación y conexiones para confirmar si el fallo está realmente en el amplificador o en otro punto de la instalación.`],[`Canales que aparecen y desaparecen`,`Comprobamos nivel y calidad por frecuencias y revisamos recepción y distribución para localizar fallos intermitentes.`],[`Instalación antigua de portero`,`Antes de sustituirla completa revisamos placa, fuente, telefonillos y cableado para saber qué elementos todavía pueden aprovecharse.`]],
[[`Antena TDT con poca calidad`,`No basta con mirar si hay señal: comprobamos también su calidad y revisamos orientación, conexiones, amplificación y distribución.`],[`Avería localizada en una comunidad`,`Si solo falla una planta o varias viviendas, seguimos esa rama de distribución para evitar cambios innecesarios en toda la instalación.`],[`Parabólica o cableado de satélite`,`Comprobamos antena, LNB, conectores y recorrido del cable para distinguir un problema de captación de una pérdida interior.`]]][v];return `<section class="town-problems" id="problemas-frecuentes"><div class="wrap"><div class="kicker">Diagnóstico técnico</div><h2>Problemas de antena que revisamos en ${n}</h2><p class="lead">Antes de sustituir equipos intentamos localizar el origen de la avería. Estas son algunas de las incidencias que podemos comprobar en viviendas y comunidades de ${n}.</p><div class="town-problems-grid">${sets.map(x=>`<article class="town-problem"><strong>${x[0]}</strong><p>${x[1]}</p></article>`).join('')}</div><div class="town-problems-cta"><a class="call" href="tel:+34641589394">Llamar 641 589 394</a><a class="wa" href="https://wa.me/34641589394">Consultar por WhatsApp</a></div></div></section>`}

for(const d of localidades){
  const file=path.join('public',d.provinciaSlug,d.slug,'index.html');
  if(!fs.existsSync(file)) continue;
  let h=fs.readFileSync(file,'utf8');
  if(!h.includes('town-backtop-style')) h=h.replace('</head>',STYLE+'</head>');
  if(!h.includes('id="problemas-frecuentes"')) h=h.replace('<section class="faq local-faq">',problems(d)+'<section class="faq local-faq">');
  if(!h.includes('class="town-backtop"')) h=h.replace('</body>',BUTTON+SCRIPT+'</body>');
  fs.writeFileSync(file,h);
}
console.log(`Extras locales aplicados a ${localidades.length} localidades: bloque técnico + volver arriba.`);
