import test from 'node:test';
import assert from 'node:assert/strict';
import { applyServiceInformation, INFORMATION, STYLE_ID } from '../service-information.mjs';

export const fixture = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Antenista en Amurrio</title><meta name="description" content="Antenista en Amurrio. Llama al 641 589 394."><meta name="robots" content="index,follow"><link rel="canonical" href="https://antenistacerca.es/alava/amurrio/"><script id="ac-cookie-runtime" src="/assets/ac-cookie-consent-v1.js" data-ga="G-W8L23NJLP6" defer></script><script id="antenistacerca-conversions">window.ACConsent?.track('click_llamada','tel:+34641589394');</script></head><body><header>ANTENISTA CERCA</header><main><h1>Antenista en Amurrio</h1><img src="/assets/hero-antenista-panorama.webp" alt="Técnico de antenas"><a href="tel:+34641589394">Llamar</a><a href="https://wa.me/34641589394">WhatsApp</a></main><footer><!-- AC-COOKIE-FOOTER-START --><div class="ac-cookie-footer" data-nosnippet><div class="ac-cookie-tools"><details id="ac-cookie-policy"><summary>Política de cookies</summary><div class="ac-cookie-policy-text"><p>Analítica desactivada hasta aceptar. Preferencias durante 180 días.</p><p>Contacto sobre esta web: <a href="tel:+34641589394">641 589 394</a>.</p></div></details><button type="button" data-ac-cookie-open>Configurar cookies</button></div></div><!-- AC-COOKIE-FOOTER-END --></footer><div id="ac-cookie-banner" hidden></div><dialog id="ac-cookie-dialog"><input type="checkbox" id="ac-cookie-analytics"><button data-ac-cookie-accept>Aceptar</button><button data-ac-cookie-reject>Rechazar</button></dialog></body></html>`;

const footerRE = /<!-- AC-COOKIE-FOOTER-START -->[\s\S]*?<!-- AC-COOKIE-FOOTER-END -->/;
const withoutChanges = html => html.replace(footerRE,'').replace(new RegExp(`<style id="${STYLE_ID}">[\\s\\S]*?<\\/style>`,'g'),'');
test('solo modifica el pie y añade estilos aislados, no HTML comercial ni SEO',()=>assert.equal(withoutChanges(applyServiceInformation(fixture)),withoutChanges(fixture)));
test('repetir no duplica iniciales, estilos ni paneles',()=>{const h=applyServiceInformation(fixture);assert.equal(applyServiceInformation(h),h);assert.equal((h.match(/id="ac-privacy-info"/g)||[]).length,1);assert.equal((h.match(/Contacto sobre esta web: R.F.G./g)||[]).length,1)});
test('conserva los scripts, controles y estado de consentimiento',()=>{const h=applyServiceInformation(fixture);const re=/<script\b[\s\S]*?<\/script>/g;assert.deepEqual(h.match(re),fixture.match(re));assert.ok(h.includes('<input type="checkbox" id="ac-cookie-analytics">'));assert.ok(h.includes('data-ac-cookie-open'));assert.ok(h.includes('data-ac-cookie-reject'));assert.ok(!h.includes('googletagmanager.com/gtag/js'))});
test('usa únicamente la identificación facilitada y señala lo que falta',()=>{assert.ok(INFORMATION.includes('R.F.G.'));assert.ok(INFORMATION.includes('641 589 394'));assert.ok(INFORMATION.includes('identificación completa del titular está pendiente'));assert.ok(!/mailto:|R\.F\.G\.\s+S\.?L\.?|Calle\s+|NIF:\s*[A-Z0-9]/.test(INFORMATION))});
test('información accesible en HTML sin JavaScript ni solicitudes de analítica',()=>{const h=applyServiceInformation(fixture);for(const id of ['ac-service-info','ac-privacy-info'])assert.ok(h.includes('<details id="'+id+'"><summary>'));assert.ok(!INFORMATION.includes('<script'));assert.ok(!INFORMATION.includes('<iframe'));assert.ok(h.includes('data-nosnippet'))});
test('falla si no existe el pie esperado o si está duplicado',()=>{assert.throws(()=>applyServiceInformation('<html><head></head><body></body></html>'),/pie/);assert.throws(()=>applyServiceInformation(fixture.replace('</footer>',fixture.match(footerRE)[0]+'</footer>')),/pie/)});
test('portada, provincia y pueblo: misma información, canonical intacto',()=>{for(const url of ['/','/alava/','/alava/amurrio/']){const h=fixture.replace('https://antenistacerca.es/alava/amurrio/','https://antenistacerca.es'+url);assert.equal(withoutChanges(applyServiceInformation(h)),withoutChanges(h))}});
